version: 2
jobs:
  build:

    branches:
      only:
       - master
   
    working_directory: ~/jacs-messaging

    docker:
      - image: circleci/openjdk:8u171-jdk

    steps:

      - checkout

      - restore_cache:
          key: jacs-messaging-{{ checksum "build.gradle" }}
      
      - run: gradle jar test
      
      - save_cache:
          key: jacs-messaging-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - store_test_results:
          paths: 
            - build/test-results/test
      
      - store_artifacts:
          path: build/libs/*.jar

