version: 2
jobs:
  build:

    branches:
      only:
       - master
   
    working_directory: ~/jacs-messaging

    docker:
      - image: circleci/openjdk:8u171-jdk

    environment:
      TERM: dumb

    steps:

      - checkout

      - restore_cache:
          keys: 
            - jacs-messaging-c1-{{ checksum "build.gradle" }}

      - run: ./gradlew --no-daemon dependencies
      
      - save_cache:
          key: jacs-messaging-c1-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - run: ./gradlew --no-daemon jar test

      - store_test_results:
          paths: 
            - build/test-results/test
